### ISSUE TITLE
activedays.py

### ISSUE THREAD

**Issue by vvvvvvpp** [expectocode/telegramAnalysis#12]
Is the average char sent on the day on the y-axis wrong? seems to be too small a number to be correct

Thank you

**Comment by tnjd** [comment]
Hi @vincentpwnz00r, honestly I haven't looked at this repo for a while since I'm in the process of transitioning to a telegram-export based analysis system, but I had a look at the code and it should indeed be the average chars sent on that day of the week. 

The relevant line is here: https://github.com/expectocode/telegram-analysis/blob/master/activedays.py#L36

However, it is worth mentioning that if there is a day where no messages are sent, this won't be counted. So if I send 100 messages over 4 different days in a week, the average chars should come to 25 (100/4) rather than 14 (100/7).
